export const LOGIN_URL = "http://localhost:3000/login"
export const SIGNUP_URL = "http://localhost:3000/signup"
export const VIEW_PROFILE = "http://localhost:3000/profile"
export const LOGOUT_URL = "http://localhost:3000/logout"
export const FEED_URL = "http://localhost:3000/user/feed"